; ###########################################
; # THIS FILE IS AUTOGENERATED, DO NOT EDIT #
; # IT IS A MIRROR OF runtime.c FILE        #
; ###########################################
; ModuleID = 'runtime.c'
source_filename = "runtime.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%struct._IO_FILE = type { i32, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, %struct._IO_marker*, %struct._IO_FILE*, i32, i32, i64, i16, i8, [1 x i8], i8*, i64, %struct._IO_codecvt*, %struct._IO_wide_data*, %struct._IO_FILE*, i8*, i64, i32, [20 x i8] }
%struct._IO_marker = type opaque
%struct._IO_codecvt = type opaque
%struct._IO_wide_data = type opaque
%struct.String = type { i32, i32, i8* }

@stderr = external local_unnamed_addr global %struct._IO_FILE*, align 8
@.str = private unnamed_addr constant [4 x i8] c"%s\0A\00", align 1
@.str.1 = private unnamed_addr constant [29 x i8] c"ERROR WHILE ALLOCATING SPACE\00", align 1
@stdout = external local_unnamed_addr global %struct._IO_FILE*, align 8
@stdin = external local_unnamed_addr global %struct._IO_FILE*, align 8
@.str.2 = private unnamed_addr constant [26 x i8] c"INVALID GETLINE ARGUMENTS\00", align 1
@.str.3 = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1
@.str.4 = private unnamed_addr constant [5 x i8] c" %d \00", align 1
@.str.5 = private unnamed_addr constant [14 x i8] c"runtime error\00", align 1

; Function Attrs: noreturn nounwind uwtable
define dso_local void @_exit_with_message(i8* noundef %0) local_unnamed_addr #0 {
  %2 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %3 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %2, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef %0) #13
  call void @exit(i32 noundef 1) #14
  unreachable
}

; Function Attrs: nofree nounwind
declare noundef i32 @fprintf(%struct._IO_FILE* nocapture noundef, i8* nocapture noundef readonly, ...) local_unnamed_addr #1

; Function Attrs: noreturn nounwind
declare void @exit(i32 noundef) local_unnamed_addr #2

; Function Attrs: nounwind uwtable
define dso_local noalias i8* @_safe_malloc(i64 noundef %0, i64 noundef %1) local_unnamed_addr #3 {
  %3 = call noalias i8* @calloc(i64 noundef %0, i64 noundef %1) #15
  %4 = icmp eq i8* %3, null
  br i1 %4, label %5, label %8

5:                                                ; preds = %2
  %6 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %7 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %6, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

8:                                                ; preds = %2
  ret i8* %3
}

; Function Attrs: argmemonly mustprogress nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #4

; Function Attrs: inaccessiblememonly mustprogress nofree nounwind willreturn
declare noalias noundef i8* @calloc(i64 noundef, i64 noundef) local_unnamed_addr #5

; Function Attrs: argmemonly mustprogress nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #4

; Function Attrs: mustprogress nofree norecurse nosync nounwind readonly uwtable willreturn
define dso_local i32 @_get_str_len(%struct.String* nocapture noundef readonly %0) local_unnamed_addr #6 {
  %2 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 0
  %3 = load i32, i32* %2, align 1, !tbaa !9
  ret i32 %3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readonly uwtable willreturn
define dso_local i8* @_get_str_data(%struct.String* nocapture noundef readonly %0) local_unnamed_addr #6 {
  %2 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 2
  %3 = load i8*, i8** %2, align 1, !tbaa !12
  ret i8* %3
}

; Function Attrs: nounwind uwtable
define dso_local noalias %struct.String* @_new_str(i8* noundef %0, i32 noundef %1, i32 noundef %2) local_unnamed_addr #3 {
  %4 = call noalias dereferenceable_or_null(16) i8* @calloc(i64 noundef 16, i64 noundef 1) #15
  %5 = icmp eq i8* %4, null
  br i1 %5, label %6, label %9

6:                                                ; preds = %3
  %7 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %8 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %7, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

9:                                                ; preds = %3
  %10 = bitcast i8* %4 to %struct.String*
  %11 = bitcast i8* %4 to i32*
  store i32 %1, i32* %11, align 1, !tbaa !9
  %12 = getelementptr inbounds i8, i8* %4, i64 8
  %13 = bitcast i8* %12 to i8**
  store i8* %0, i8** %13, align 1, !tbaa !12
  %14 = getelementptr inbounds i8, i8* %4, i64 4
  %15 = bitcast i8* %14 to i32*
  store i32 %2, i32* %15, align 1, !tbaa !13
  ret %struct.String* %10
}

; Function Attrs: nounwind uwtable
define dso_local noalias %struct.String* @_new_str_from_literal(i8* noundef %0, i32 noundef %1) local_unnamed_addr #3 {
  %3 = call noalias dereferenceable_or_null(16) i8* @calloc(i64 noundef 16, i64 noundef 1) #15
  %4 = icmp eq i8* %3, null
  br i1 %4, label %5, label %8

5:                                                ; preds = %2
  %6 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %7 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %6, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

8:                                                ; preds = %2
  %9 = bitcast i8* %3 to %struct.String*
  %10 = bitcast i8* %3 to i32*
  store i32 %1, i32* %10, align 1, !tbaa !9
  %11 = getelementptr inbounds i8, i8* %3, i64 8
  %12 = bitcast i8* %11 to i8**
  store i8* %0, i8** %12, align 1, !tbaa !12
  %13 = getelementptr inbounds i8, i8* %3, i64 4
  %14 = bitcast i8* %13 to i32*
  store i32 0, i32* %14, align 1, !tbaa !13
  ret %struct.String* %9
}

; Function Attrs: mustprogress nounwind uwtable willreturn
define dso_local void @_remove_str(%struct.String* nocapture noundef %0) local_unnamed_addr #7 {
  %2 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 1
  %3 = load i32, i32* %2, align 1, !tbaa !13
  %4 = icmp eq i32 %3, 0
  br i1 %4, label %8, label %5

5:                                                ; preds = %1
  %6 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 2
  %7 = load i8*, i8** %6, align 1, !tbaa !12
  call void @free(i8* noundef %7) #15
  store i8* null, i8** %6, align 1, !tbaa !12
  br label %8

8:                                                ; preds = %5, %1
  %9 = bitcast %struct.String* %0 to i8*
  call void @free(i8* noundef %9) #15
  ret void
}

; Function Attrs: inaccessiblemem_or_argmemonly mustprogress nounwind willreturn
declare void @free(i8* nocapture noundef) local_unnamed_addr #8

; Function Attrs: nounwind uwtable
define dso_local noalias %struct.String* @_concat_str(%struct.String* nocapture noundef readonly %0, %struct.String* nocapture noundef readonly %1) local_unnamed_addr #3 {
  %3 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 0
  %4 = load i32, i32* %3, align 1, !tbaa !9
  %5 = getelementptr inbounds %struct.String, %struct.String* %1, i64 0, i32 0
  %6 = load i32, i32* %5, align 1, !tbaa !9
  %7 = add nsw i32 %6, %4
  %8 = sext i32 %7 to i64
  %9 = call noalias i8* @calloc(i64 noundef %8, i64 noundef 1) #15
  %10 = icmp eq i8* %9, null
  br i1 %10, label %11, label %14

11:                                               ; preds = %2
  %12 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %13 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %12, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

14:                                               ; preds = %2
  %15 = call noalias dereferenceable_or_null(16) i8* @calloc(i64 noundef 16, i64 noundef 1) #15
  %16 = icmp eq i8* %15, null
  br i1 %16, label %17, label %20

17:                                               ; preds = %14
  %18 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %19 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %18, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

20:                                               ; preds = %14
  %21 = bitcast i8* %15 to %struct.String*
  %22 = bitcast i8* %15 to i32*
  store i32 %7, i32* %22, align 1, !tbaa !9
  %23 = getelementptr inbounds i8, i8* %15, i64 8
  %24 = bitcast i8* %23 to i8**
  store i8* %9, i8** %24, align 1, !tbaa !12
  %25 = getelementptr inbounds i8, i8* %15, i64 4
  %26 = bitcast i8* %25 to i32*
  store i32 1, i32* %26, align 1, !tbaa !13
  %27 = getelementptr inbounds %struct.String, %struct.String* %21, i64 0, i32 2
  %28 = load i8*, i8** %27, align 1, !tbaa !12
  %29 = load i32, i32* %3, align 1, !tbaa !9
  %30 = icmp sgt i32 %29, 0
  br i1 %30, label %31, label %33

31:                                               ; preds = %20
  %32 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 2
  br label %39

33:                                               ; preds = %39, %20
  %34 = phi i8* [ %28, %20 ], [ %45, %39 ]
  %35 = load i32, i32* %5, align 1, !tbaa !9
  %36 = icmp sgt i32 %35, 0
  br i1 %36, label %37, label %50

37:                                               ; preds = %33
  %38 = getelementptr inbounds %struct.String, %struct.String* %1, i64 0, i32 2
  br label %51

39:                                               ; preds = %31, %39
  %40 = phi i64 [ 0, %31 ], [ %46, %39 ]
  %41 = phi i8* [ %28, %31 ], [ %45, %39 ]
  %42 = load i8*, i8** %32, align 1, !tbaa !12
  %43 = getelementptr inbounds i8, i8* %42, i64 %40
  %44 = load i8, i8* %43, align 1, !tbaa !14
  %45 = getelementptr inbounds i8, i8* %41, i64 1
  store i8 %44, i8* %41, align 1, !tbaa !14
  %46 = add nuw nsw i64 %40, 1
  %47 = load i32, i32* %3, align 1, !tbaa !9
  %48 = sext i32 %47 to i64
  %49 = icmp slt i64 %46, %48
  br i1 %49, label %39, label %33, !llvm.loop !15

50:                                               ; preds = %51, %33
  ret %struct.String* %21

51:                                               ; preds = %37, %51
  %52 = phi i64 [ 0, %37 ], [ %58, %51 ]
  %53 = phi i8* [ %34, %37 ], [ %57, %51 ]
  %54 = load i8*, i8** %38, align 1, !tbaa !12
  %55 = getelementptr inbounds i8, i8* %54, i64 %52
  %56 = load i8, i8* %55, align 1, !tbaa !14
  %57 = getelementptr inbounds i8, i8* %53, i64 1
  store i8 %56, i8* %53, align 1, !tbaa !14
  %58 = add nuw nsw i64 %52, 1
  %59 = load i32, i32* %5, align 1, !tbaa !9
  %60 = sext i32 %59 to i64
  %61 = icmp slt i64 %58, %60
  br i1 %61, label %51, label %50, !llvm.loop !18
}

; Function Attrs: nofree norecurse nosync nounwind readonly uwtable
define dso_local i32 @_str_eq(%struct.String* nocapture noundef readonly %0, %struct.String* nocapture noundef readonly %1) local_unnamed_addr #9 {
  %3 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 0
  %4 = load i32, i32* %3, align 1, !tbaa !9
  %5 = getelementptr inbounds %struct.String, %struct.String* %1, i64 0, i32 0
  %6 = load i32, i32* %5, align 1, !tbaa !9
  %7 = icmp eq i32 %4, %6
  br i1 %7, label %8, label %36

8:                                                ; preds = %2
  %9 = icmp sgt i32 %4, 0
  br i1 %9, label %10, label %32

10:                                               ; preds = %8
  %11 = getelementptr inbounds %struct.String, %struct.String* %1, i64 0, i32 2
  %12 = load i8*, i8** %11, align 1, !tbaa !12
  %13 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 2
  %14 = load i8*, i8** %13, align 1, !tbaa !12
  %15 = load i8, i8* %14, align 1, !tbaa !14
  %16 = load i8, i8* %12, align 1, !tbaa !14
  %17 = icmp eq i8 %15, %16
  br i1 %17, label %22, label %32

18:                                               ; preds = %22
  %19 = load i8, i8* %27, align 1, !tbaa !14
  %20 = load i8, i8* %26, align 1, !tbaa !14
  %21 = icmp eq i8 %19, %20
  br i1 %21, label %22, label %30, !llvm.loop !19

22:                                               ; preds = %10, %18
  %23 = phi i8* [ %27, %18 ], [ %14, %10 ]
  %24 = phi i8* [ %26, %18 ], [ %12, %10 ]
  %25 = phi i32 [ %28, %18 ], [ 0, %10 ]
  %26 = getelementptr inbounds i8, i8* %24, i64 1
  %27 = getelementptr inbounds i8, i8* %23, i64 1
  %28 = add nuw nsw i32 %25, 1
  %29 = icmp eq i32 %28, %4
  br i1 %29, label %30, label %18, !llvm.loop !19

30:                                               ; preds = %22, %18
  %31 = icmp slt i32 %28, %4
  br label %32

32:                                               ; preds = %30, %10, %8
  %33 = phi i1 [ %9, %8 ], [ %9, %10 ], [ %31, %30 ]
  %34 = xor i1 %33, true
  %35 = zext i1 %34 to i32
  br label %36

36:                                               ; preds = %2, %32
  %37 = phi i32 [ %35, %32 ], [ 0, %2 ]
  ret i32 %37
}

; Function Attrs: nofree norecurse nosync nounwind readonly uwtable
define dso_local i32 @_str_neq(%struct.String* nocapture noundef readonly %0, %struct.String* nocapture noundef readonly %1) local_unnamed_addr #9 {
  %3 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 0
  %4 = load i32, i32* %3, align 1, !tbaa !9
  %5 = getelementptr inbounds %struct.String, %struct.String* %1, i64 0, i32 0
  %6 = load i32, i32* %5, align 1, !tbaa !9
  %7 = icmp eq i32 %4, %6
  br i1 %7, label %8, label %35

8:                                                ; preds = %2
  %9 = icmp sgt i32 %4, 0
  br i1 %9, label %10, label %32

10:                                               ; preds = %8
  %11 = getelementptr inbounds %struct.String, %struct.String* %1, i64 0, i32 2
  %12 = load i8*, i8** %11, align 1, !tbaa !12
  %13 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 2
  %14 = load i8*, i8** %13, align 1, !tbaa !12
  %15 = load i8, i8* %14, align 1, !tbaa !14
  %16 = load i8, i8* %12, align 1, !tbaa !14
  %17 = icmp eq i8 %15, %16
  br i1 %17, label %22, label %32

18:                                               ; preds = %22
  %19 = load i8, i8* %27, align 1, !tbaa !14
  %20 = load i8, i8* %26, align 1, !tbaa !14
  %21 = icmp eq i8 %19, %20
  br i1 %21, label %22, label %30, !llvm.loop !19

22:                                               ; preds = %10, %18
  %23 = phi i8* [ %27, %18 ], [ %14, %10 ]
  %24 = phi i8* [ %26, %18 ], [ %12, %10 ]
  %25 = phi i32 [ %28, %18 ], [ 0, %10 ]
  %26 = getelementptr inbounds i8, i8* %24, i64 1
  %27 = getelementptr inbounds i8, i8* %23, i64 1
  %28 = add nuw nsw i32 %25, 1
  %29 = icmp eq i32 %28, %4
  br i1 %29, label %30, label %18, !llvm.loop !19

30:                                               ; preds = %22, %18
  %31 = icmp slt i32 %28, %4
  br label %32

32:                                               ; preds = %30, %10, %8
  %33 = phi i1 [ %9, %8 ], [ true, %10 ], [ %31, %30 ]
  %34 = zext i1 %33 to i32
  br label %35

35:                                               ; preds = %2, %32
  %36 = phi i32 [ %34, %32 ], [ 1, %2 ]
  ret i32 %36
}

; Function Attrs: nofree nounwind uwtable
define dso_local void @printString(%struct.String* nocapture noundef readonly %0) local_unnamed_addr #10 {
  %2 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 0
  %3 = load i32, i32* %2, align 1, !tbaa !9
  %4 = icmp sgt i32 %3, 0
  br i1 %4, label %5, label %7

5:                                                ; preds = %1
  %6 = getelementptr inbounds %struct.String, %struct.String* %0, i64 0, i32 2
  br label %12

7:                                                ; preds = %12, %1
  %8 = load %struct._IO_FILE*, %struct._IO_FILE** @stdout, align 8, !tbaa !5
  %9 = call i32 @putc(i32 noundef 10, %struct._IO_FILE* noundef %8) #15
  %10 = load %struct._IO_FILE*, %struct._IO_FILE** @stdout, align 8, !tbaa !5
  %11 = call i32 @fflush(%struct._IO_FILE* noundef %10)
  ret void

12:                                               ; preds = %5, %12
  %13 = phi i64 [ 0, %5 ], [ %20, %12 ]
  %14 = load i8*, i8** %6, align 1, !tbaa !12
  %15 = getelementptr inbounds i8, i8* %14, i64 %13
  %16 = load i8, i8* %15, align 1, !tbaa !14
  %17 = sext i8 %16 to i32
  %18 = load %struct._IO_FILE*, %struct._IO_FILE** @stdout, align 8, !tbaa !5
  %19 = call i32 @putc(i32 noundef %17, %struct._IO_FILE* noundef %18) #15
  %20 = add nuw nsw i64 %13, 1
  %21 = load i32, i32* %2, align 1, !tbaa !9
  %22 = sext i32 %21 to i64
  %23 = icmp slt i64 %20, %22
  br i1 %23, label %12, label %7, !llvm.loop !20
}

; Function Attrs: nofree nounwind
declare noundef i32 @fflush(%struct._IO_FILE* nocapture noundef) local_unnamed_addr #1

; Function Attrs: nounwind uwtable
define dso_local noalias %struct.String* @readString() local_unnamed_addr #3 {
  %1 = alloca i8*, align 8
  %2 = alloca i64, align 8
  %3 = bitcast i8** %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %3) #15
  store i8* null, i8** %1, align 8, !tbaa !5
  %4 = bitcast i64* %2 to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %4) #15
  store i64 0, i64* %2, align 8, !tbaa !21
  %5 = call i32* @__errno_location() #17
  store i32 0, i32* %5, align 4, !tbaa !23
  %6 = load %struct._IO_FILE*, %struct._IO_FILE** @stdin, align 8, !tbaa !5
  %7 = call i64 @getline(i8** noundef nonnull %1, i64* noundef nonnull %2, %struct._IO_FILE* noundef %6) #15
  %8 = load i32, i32* %5, align 4, !tbaa !23
  switch i32 %8, label %15 [
    i32 22, label %9
    i32 12, label %12
  ]

9:                                                ; preds = %0
  %10 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %11 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %10, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([26 x i8], [26 x i8]* @.str.2, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

12:                                               ; preds = %0
  %13 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %14 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %13, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

15:                                               ; preds = %0
  %16 = icmp eq i64 %7, 0
  br i1 %16, label %24, label %17

17:                                               ; preds = %15
  %18 = load i8*, i8** %1, align 8, !tbaa !5
  %19 = add i64 %7, -1
  %20 = getelementptr inbounds i8, i8* %18, i64 %19
  %21 = load i8, i8* %20, align 1, !tbaa !14
  %22 = icmp eq i8 %21, 10
  br i1 %22, label %23, label %24

23:                                               ; preds = %17
  store i8 0, i8* %20, align 1, !tbaa !14
  br label %24

24:                                               ; preds = %23, %17, %15
  %25 = phi i64 [ %19, %23 ], [ %7, %17 ], [ 0, %15 ]
  %26 = load i8*, i8** %1, align 8, !tbaa !5
  %27 = call noalias dereferenceable_or_null(16) i8* @calloc(i64 noundef 16, i64 noundef 1) #15
  %28 = icmp eq i8* %27, null
  br i1 %28, label %29, label %32

29:                                               ; preds = %24
  %30 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %31 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %30, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

32:                                               ; preds = %24
  %33 = trunc i64 %25 to i32
  %34 = bitcast i8* %27 to %struct.String*
  %35 = bitcast i8* %27 to i32*
  store i32 %33, i32* %35, align 1, !tbaa !9
  %36 = getelementptr inbounds i8, i8* %27, i64 8
  %37 = bitcast i8* %36 to i8**
  store i8* %26, i8** %37, align 1, !tbaa !12
  %38 = getelementptr inbounds i8, i8* %27, i64 4
  %39 = bitcast i8* %38 to i32*
  store i32 1, i32* %39, align 1, !tbaa !13
  %40 = getelementptr inbounds %struct.String, %struct.String* %34, i64 0, i32 1
  store i32 1, i32* %40, align 1, !tbaa !13
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %4) #15
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %3) #15
  ret %struct.String* %34
}

; Function Attrs: mustprogress nofree nosync nounwind readnone willreturn
declare i32* @__errno_location() local_unnamed_addr #11

declare i64 @getline(i8** noundef, i64* noundef, %struct._IO_FILE* noundef) local_unnamed_addr #12

; Function Attrs: nofree nounwind uwtable
define dso_local void @printInt(i32 noundef %0) local_unnamed_addr #10 {
  %2 = call i32 (i8*, ...) @printf(i8* noundef nonnull dereferenceable(1) getelementptr inbounds ([4 x i8], [4 x i8]* @.str.3, i64 0, i64 0), i32 noundef %0)
  %3 = load %struct._IO_FILE*, %struct._IO_FILE** @stdout, align 8, !tbaa !5
  %4 = call i32 @fflush(%struct._IO_FILE* noundef %3)
  ret void
}

; Function Attrs: nofree nounwind
declare noundef i32 @printf(i8* nocapture noundef readonly, ...) local_unnamed_addr #1

; Function Attrs: nofree nounwind uwtable
define dso_local i32 @readInt() local_unnamed_addr #10 {
  %1 = alloca i32, align 4
  %2 = bitcast i32* %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* nonnull %2) #15
  %3 = call i32 (i8*, ...) @__isoc99_scanf(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.4, i64 0, i64 0), i32* noundef nonnull %1)
  %4 = load i32, i32* %1, align 4, !tbaa !23
  call void @llvm.lifetime.end.p0i8(i64 4, i8* nonnull %2) #15
  ret i32 %4
}

; Function Attrs: nofree nounwind
declare noundef i32 @__isoc99_scanf(i8* nocapture noundef readonly, ...) local_unnamed_addr #1

; Function Attrs: noreturn nounwind uwtable
define dso_local void @error() local_unnamed_addr #0 {
  %1 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %2 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %1, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @.str.5, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable
}

; Function Attrs: nounwind uwtable
define dso_local noalias i8* @_memory_allocate(i32 noundef %0) local_unnamed_addr #3 {
  %2 = sext i32 %0 to i64
  %3 = call noalias i8* @calloc(i64 noundef 1, i64 noundef %2) #15
  %4 = icmp eq i8* %3, null
  br i1 %4, label %5, label %8

5:                                                ; preds = %1
  %6 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %7 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %6, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

8:                                                ; preds = %1
  ret i8* %3
}

; Function Attrs: nounwind uwtable
define dso_local noalias i8* @_memory_allocate_many(i32 noundef %0, i32 noundef %1) local_unnamed_addr #3 {
  %3 = sext i32 %0 to i64
  %4 = sext i32 %1 to i64
  %5 = call noalias i8* @calloc(i64 noundef %3, i64 noundef %4) #15
  %6 = icmp eq i8* %5, null
  br i1 %6, label %7, label %10

7:                                                ; preds = %2
  %8 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %9 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %8, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

10:                                               ; preds = %2
  ret i8* %5
}

; Function Attrs: mustprogress nounwind uwtable willreturn
define dso_local void @_memory_free(i8* nocapture noundef %0) local_unnamed_addr #7 {
  call void @free(i8* noundef %0) #15
  ret void
}

; Function Attrs: nounwind uwtable
define dso_local noalias i8* @_memory_allocate_many_strings(i32 noundef %0, i8* noundef %1) local_unnamed_addr #3 {
  %3 = sext i32 %0 to i64
  %4 = call noalias i8* @calloc(i64 noundef %3, i64 noundef 8) #15
  %5 = icmp eq i8* %4, null
  br i1 %5, label %6, label %9

6:                                                ; preds = %2
  %7 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %8 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %7, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

9:                                                ; preds = %2
  %10 = bitcast i8* %4 to %struct.String**
  %11 = call noalias dereferenceable_or_null(16) i8* @calloc(i64 noundef 16, i64 noundef 1) #15
  %12 = icmp eq i8* %11, null
  br i1 %12, label %13, label %16

13:                                               ; preds = %9
  %14 = load %struct._IO_FILE*, %struct._IO_FILE** @stderr, align 8, !tbaa !5
  %15 = call i32 (%struct._IO_FILE*, i8*, ...) @fprintf(%struct._IO_FILE* noundef %14, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8* noundef getelementptr inbounds ([29 x i8], [29 x i8]* @.str.1, i64 0, i64 0)) #16
  call void @exit(i32 noundef 1) #14
  unreachable

16:                                               ; preds = %9
  %17 = bitcast i8* %11 to i32*
  store i32 0, i32* %17, align 1, !tbaa !9
  %18 = getelementptr inbounds i8, i8* %11, i64 8
  %19 = bitcast i8* %18 to i8**
  store i8* %1, i8** %19, align 1, !tbaa !12
  %20 = getelementptr inbounds i8, i8* %11, i64 4
  %21 = bitcast i8* %20 to i32*
  store i32 0, i32* %21, align 1, !tbaa !13
  %22 = icmp sgt i32 %0, 0
  br i1 %22, label %23, label %25

23:                                               ; preds = %16
  %24 = zext i32 %0 to i64
  br label %26

25:                                               ; preds = %26, %16
  ret i8* %4

26:                                               ; preds = %23, %26
  %27 = phi i64 [ 0, %23 ], [ %30, %26 ]
  %28 = getelementptr inbounds %struct.String*, %struct.String** %10, i64 %27
  %29 = bitcast %struct.String** %28 to i8**
  store i8* %11, i8** %29, align 8, !tbaa !5
  %30 = add nuw nsw i64 %27, 1
  %31 = icmp eq i64 %30, %24
  br i1 %31, label %25, label %26, !llvm.loop !24
}

; Function Attrs: nofree nounwind
declare noundef i32 @putc(i32 noundef, %struct._IO_FILE* nocapture noundef) local_unnamed_addr #1

attributes #0 = { noreturn nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { nofree nounwind "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { noreturn nounwind "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #3 = { nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #4 = { argmemonly mustprogress nofree nosync nounwind willreturn }
attributes #5 = { inaccessiblememonly mustprogress nofree nounwind willreturn "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #6 = { mustprogress nofree norecurse nosync nounwind readonly uwtable willreturn "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #7 = { mustprogress nounwind uwtable willreturn "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #8 = { inaccessiblemem_or_argmemonly mustprogress nounwind willreturn "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #9 = { nofree norecurse nosync nounwind readonly uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #10 = { nofree nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #11 = { mustprogress nofree nosync nounwind readnone willreturn "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #12 = { "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #13 = { cold }
attributes #14 = { noreturn nounwind }
attributes #15 = { nounwind }
attributes #16 = { cold nounwind }
attributes #17 = { nounwind readnone willreturn }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 1}
!4 = !{!"Ubuntu clang version 14.0.0-1ubuntu1.1"}
!5 = !{!6, !6, i64 0}
!6 = !{!"any pointer", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !11, i64 0}
!10 = !{!"", !11, i64 0, !11, i64 4, !6, i64 8}
!11 = !{!"int", !7, i64 0}
!12 = !{!10, !6, i64 8}
!13 = !{!10, !11, i64 4}
!14 = !{!7, !7, i64 0}
!15 = distinct !{!15, !16, !17}
!16 = !{!"llvm.loop.mustprogress"}
!17 = !{!"llvm.loop.unroll.disable"}
!18 = distinct !{!18, !16, !17}
!19 = distinct !{!19, !16, !17}
!20 = distinct !{!20, !16, !17}
!21 = !{!22, !22, i64 0}
!22 = !{!"long", !7, i64 0}
!23 = !{!11, !11, i64 0}
!24 = distinct !{!24, !16, !17}
