name: CMake on Unix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [ Release, Debug ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: 'mpich'

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: install libboost-all-dev
          version: 1.0

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}} -- -j

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build-type}} --output-on-failure
