-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelExp where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsExp

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExp :: Show a => AbsExp.Exp' a -> Result
transExp x = case x of
  AbsExp.EMul _ exp1 exp2 -> failure x
  AbsExp.EAdd _ exp1 exp2 -> failure x
  AbsExp.EInt _ integer -> failure x
